### ISSUE TITLE
My $.02

### ISSUE THREAD

**Issue by faddat** [l0k1-smirenski/docker-gentoo-steemd#2]
It seems to me like you may be treating docker a little too much like a virtual machine.  They're totally not virtual machines, though, as they execute against the host kernel and not the OS kernel.  For this reason, alpine linux is popular these days for stuff like this.  If you are using gentoo only for build environment, the docker best practices for this would be actually (and I hate this part) to use docker-in-docker in order to build in gentoo (using all the optimizations that you're able to because that you're using gentoo.) and then use COPY in the Dockerfile inside of the first Dockerfile to move the built stuff into the filesystem of the docker that is within the docker.  

This is MERELY best-practices.  Your way works, and that trumps all in the end.

**Comment by l0k18** [comment]
The way I have been using it is like a regular system (so, comparable to a VM) but one that I can build bit by bit until everything is correct. The overlay layers docker creates act like snapshots, which allows me to incrementally implement it.
